### ISSUE TITLE
[Feature Request] Drift.com Left/Right Align

### ISSUE THREAD

**Issue by johncjensen** [calibreapp/react-live-chat-loader#138] opened 2022-07-07 22:47 UTC
### What problem would this feature solve?

Allowing left alignment of Drift widget

### Describe the solution you’d like to see

Adding component props for left (right default) for Drift

Alternatively, can you place an ID or Class on the div that contains the button so I can target it via CSS for left alignment?

### Are you willing to work on implementing this solution?

No

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment] 2022-07-13 05:27
Going to call this a dupe of #92.

**Closed by benschwarz** 2022-07-13 05:27 UTC
Labels: enhancement
