### ISSUE TITLE
[Bug] HelpScout doesn't toggle off

### ISSUE THREAD

**Issue by mitul-s** [calibreapp/react-live-chat-loader#143] opened 2022-07-27 19:49 UTC
### Describe the bug

HelpScout's state to see if it's open or closed doesn't seem to work. Once you open it, you can't close it unless you click HelpScout's specific close button.

You can see it happening in the demo docs as well:
[https://react-live-chat-loader.vercel.app/helpscout](https://react-live-chat-loader.vercel.app/helpscout) 

### How To Reproduce

1. Set up a HelpScout provider chat 
2. Try to open it in your app
3. Try to close it 

### Screenshots

![CleanShot 2022-07-27 at 15 49 06](https://user-images.githubusercontent.com/19615826/181359563-11e1b547-4639-42e4-858c-aead9d86290b.gif)

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by Josefnm** [comment] 2022-11-10 17:49
i had the same issue with intercom. Seems like "someone" had added it via Google Tag manager, so it was loading eagerly which messes up the logic in react-live-chat-loader. You could maybe look into if someone has added a script to load it somewhere else in your case as well?

**Comment by benschwarz** [comment] 2023-06-23 00:00
Closing: Dupe of #141

**Closed by benschwarz** 2023-06-23 00:00 UTC
Labels: bug
